const translations = {
  common: {
    en: {
      navPrivacy: "Privacy",
      navSupport: "Support",
      navCopyright: "Copyright",
      languageLabel: "Language selector",
      footerNote: "© 2025 GlowLab AI. All rights reserved.",
      footerSupport: "Support: smfedorov.iosdev@gmail.com"
    },
    es: {
      navPrivacy: "Privacidad",
      navSupport: "Soporte",
      navCopyright: "Derechos de autor",
      languageLabel: "Selector de idioma",
      footerNote: "© 2025 GlowLab AI. Todos los derechos reservados.",
      footerSupport: "Soporte: smfedorov.iosdev@gmail.com"
    },
    ru: {
      navPrivacy: "Конфиденциальность",
      navSupport: "Поддержка",
      navCopyright: "Авторские права",
      languageLabel: "Выбор языка",
      footerNote: "© 2025 GlowLab AI. Все права защищены.",
      footerSupport: "Поддержка: smfedorov.iosdev@gmail.com"
    },
    de: {
      navPrivacy: "Datenschutz",
      navSupport: "Support",
      navCopyright: "Urheberrecht",
      languageLabel: "Sprachauswahl",
      footerNote: "© 2025 GlowLab AI. Alle Rechte vorbehalten.",
      footerSupport: "Support: smfedorov.iosdev@gmail.com"
    },
    it: {
      navPrivacy: "Privacy",
      navSupport: "Supporto",
      navCopyright: "Copyright",
      languageLabel: "Selettore lingua",
      footerNote: "© 2025 GlowLab AI. Tutti i diritti riservati.",
      footerSupport: "Supporto: smfedorov.iosdev@gmail.com"
    },
    fr: {
      navPrivacy: "Confidentialité",
      navSupport: "Support",
      navCopyright: "Droits d'auteur",
      languageLabel: "Sélecteur de langue",
      footerNote: "© 2025 GlowLab AI. Tous droits réservés.",
      footerSupport: "Support : smfedorov.iosdev@gmail.com"
    }
  },
  home: {
    en: {
      heroBadge: "Personalized calm for day and night",
      heroTitle: "Drift into calm with GlowLab AI",
      heroSubtitle: "GlowLab AI blends adaptive sleep sounds with immersive visuals so you can relax faster, sleep deeper, and wake up refreshed.",
      heroPrimaryCta: "Download on the App Store",
      heroSecondaryCta: "Contact support",
      heroNote: "App Store link coming soon.",
      heroPointOne: "One-tap playback without ads or sign-ups.",
      heroPointTwo: "Seamless loops with gentle fades for uninterrupted rest.",
      heroPointThree: "Timer and Apple Watch controls keep you in flow.",
      storeTitle: "Ready for your nighttime routine",
      storeSubtitle: "Save this page and tap the button once the App Store link is live.",
      storeButton: "App Store - Coming soon",
      featuresTitle: "Sleep-enhancing highlights",
      feature1Title: "Adaptive AI soundscapes",
      feature1Body: "Choose curated mixes crafted for deep sleep, focus, or gentle relaxation.",
      feature2Title: "Immersive ambient visuals",
      feature2Body: "Soft gradients and animated flows keep your room calm without distractions.",
      feature3Title: "Timer that fits your rhythm",
      feature3Body: "Set precise fade-outs so the sound stops the moment you fall asleep.",
      feature4Title: "Apple Watch support",
      feature4Body: "Start, pause, and adjust right from your wrist with haptics that guide you softly.",
      screenshotsTitle: "Inside GlowLab AI",
      screenshotsSubtitle: "Preview the app experience before you download."
    },
    es: {
      heroBadge: "Calma personalizada para el día y la noche",
      heroTitle: "Relájate con GlowLab AI",
      heroSubtitle: "GlowLab AI combina sonidos adaptativos y visuales envolventes para ayudarte a relajarte más rápido, dormir mejor y despertar renovado.",
      heroPrimaryCta: "Descargar en App Store",
      heroSecondaryCta: "Contactar soporte",
      heroNote: "Enlace de App Store disponible pronto.",
      heroPointOne: "Reproducción con un solo toque, sin anuncios ni registros.",
      heroPointTwo: "Bucles continuos con desvanecidos suaves para un descanso sin interrupciones.",
      heroPointThree: "Temporizador y control desde Apple Watch para mantener tu ritmo.",
      storeTitle: "Listo para tu rutina nocturna",
      storeSubtitle: "Guarda esta página y toca el botón cuando el enlace de App Store esté disponible.",
      storeButton: "App Store - Próximamente",
      featuresTitle: "Destacados para mejorar tu descanso",
      feature1Title: "Paisajes sonoros adaptativos con IA",
      feature1Body: "Elige mezclas curadas para sueño profundo, concentración o relajación suave.",
      feature2Title: "Visuales ambientales envolventes",
      feature2Body: "Gradientes suaves y animaciones tranquilas sin distracciones.",
      feature3Title: "Temporizador a tu ritmo",
      feature3Body: "Define desvanecidos precisos para que el sonido se detenga al quedarte dormido.",
      feature4Title: "Compatibilidad con Apple Watch",
      feature4Body: "Inicia, pausa y ajusta desde tu muñeca con suaves hápticos.",
      screenshotsTitle: "Dentro de GlowLab AI",
      screenshotsSubtitle: "Previsualiza la experiencia antes de descargar."
    },
    ru: {
      heroBadge: "Персональная атмосфера спокойствия днём и ночью",
      heroTitle: "Расслабьтесь с GlowLab AI",
      heroSubtitle: "GlowLab AI сочетает адаптивные звуки сна и мягкие визуальные сцены, чтобы вы быстрее расслаблялись, глубже спали и просыпались бодрыми.",
      heroPrimaryCta: "Скачать в App Store",
      heroSecondaryCta: "Связаться с поддержкой",
      heroNote: "Ссылка на App Store появится скоро.",
      heroPointOne: "Запуск в одно касание без рекламы и регистрации.",
      heroPointTwo: "Бесшовные петли со спокойными затуханиями для непрерывного отдыха.",
      heroPointThree: "Таймер и управление с Apple Watch сохраняют ваш ритм.",
      storeTitle: "Готово к вашему вечернему ритуалу",
      storeSubtitle: "Сохраните эту страницу и нажмите кнопку, когда ссылка на App Store станет доступна.",
      storeButton: "App Store - скоро",
      featuresTitle: "Главные преимущества для сна",
      feature1Title: "Адаптивные звуковые ландшафты",
      feature1Body: "Выбирайте подобранные миксы для глубокого сна, фокуса или мягкого отдыха.",
      feature2Title: "Погружающие визуальные эффекты",
      feature2Body: "Нежные градиенты и анимации создают спокойствие без отвлечений.",
      feature3Title: "Таймер под ваш ритм",
      feature3Body: "Настраивайте плавное затухание, чтобы звук стихал, когда вы засыпаете.",
      feature4Title: "Поддержка Apple Watch",
      feature4Body: "Запускайте, ставьте на паузу и управляйте со своего запястья с мягкой тактильной отдачей.",
      screenshotsTitle: "Интерфейс GlowLab AI",
      screenshotsSubtitle: "Оцените приложение перед скачиванием."
    },
    de: {
      heroBadge: "Personalisierte Ruhe für Tag und Nacht",
      heroTitle: "Finde zur Ruhe mit GlowLab AI",
      heroSubtitle: "GlowLab AI kombiniert adaptive Schlafklänge mit immersiven Visuals, damit du schneller entspannst, tiefer schläfst und erholt erwachst.",
      heroPrimaryCta: "Im App Store laden",
      heroSecondaryCta: "Support kontaktieren",
      heroNote: "App-Store-Link folgt in Kürze.",
      heroPointOne: "Wiedergabe mit einem Tipp, ganz ohne Werbung oder Registrierung.",
      heroPointTwo: "Nahtlose Loops mit sanften Ausblendungen für ungestörte Ruhe.",
      heroPointThree: "Timer und Apple-Watch-Steuerung halten deinen Rhythmus.",
      storeTitle: "Bereit für deine Abendroutine",
      storeSubtitle: "Speichere diese Seite und tippe auf den Button, sobald der App-Store-Link aktiv ist.",
      storeButton: "App Store - Demnächst",
      featuresTitle: "Highlights für besseren Schlaf",
      feature1Title: "Adaptive KI-Klanglandschaften",
      feature1Body: "Wähle kuratierte Mixes für Tiefschlaf, Fokus oder sanfte Entspannung.",
      feature2Title: "Immersive Ambient-Visuals",
      feature2Body: "Weiche Verläufe und Animationen sorgen für Ruhe ohne Ablenkung.",
      feature3Title: "Timer im eigenen Rhythmus",
      feature3Body: "Stelle präzise Ausblendungen ein, damit der Klang endet, wenn du einschläfst.",
      feature4Title: "Apple-Watch-Unterstützung",
      feature4Body: "Start, Pause und Anpassung bequem vom Handgelenk mit sanften Haptics.",
      screenshotsTitle: "Einblicke in GlowLab AI",
      screenshotsSubtitle: "Erlebe die App, bevor du sie herunterlädst."
    },
    it: {
      heroBadge: "Calma personalizzata per giorno e notte",
      heroTitle: "Ritrova la tranquillità con GlowLab AI",
      heroSubtitle: "GlowLab AI unisce suoni del sonno adattivi e visualizzazioni immersive per aiutarti a rilassarti, dormire profondamente e svegliarti rigenerato.",
      heroPrimaryCta: "Scarica su App Store",
      heroSecondaryCta: "Contatta il supporto",
      heroNote: "Il link dell'App Store sarà disponibile a breve.",
      heroPointOne: "Riproduzione immediata senza pubblicità o registrazioni.",
      heroPointTwo: "Loop fluidi con dissolvenze morbide per un riposo continuo.",
      heroPointThree: "Timer e controlli Apple Watch seguono il tuo ritmo.",
      storeTitle: "Pronto per la tua routine serale",
      storeSubtitle: "Salva questa pagina e tocca il pulsante quando il link sarà attivo.",
      storeButton: "App Store - In arrivo",
      featuresTitle: "Punti di forza per migliorare il sonno",
      feature1Title: "Paesaggi sonori adattivi IA",
      feature1Body: "Scegli mix curati per sonno profondo, concentrazione o relax leggero.",
      feature2Title: "Visual ambient immersivi",
      feature2Body: "Gradienti morbidi e animazioni tranquille senza distrazioni.",
      feature3Title: "Timer su misura",
      feature3Body: "Imposta dissolvenze precise perché il suono si arresti quando ti addormenti.",
      feature4Title: "Supporto Apple Watch",
      feature4Body: "Avvia, metti in pausa e regola dal polso con feedback delicati.",
      screenshotsTitle: "Dentro GlowLab AI",
      screenshotsSubtitle: "Scopri l'esperienza dell'app prima di scaricarla."
    },
    fr: {
      heroBadge: "Calme personnalisé jour et nuit",
      heroTitle: "Retrouvez la sérénité avec GlowLab AI",
      heroSubtitle: "GlowLab AI combine sons adaptatifs et visuels immersifs pour vous aider à vous détendre plus vite, dormir profondément et vous réveiller reposé.",
      heroPrimaryCta: "Télécharger sur l'App Store",
      heroSecondaryCta: "Contacter le support",
      heroNote: "Lien App Store disponible bientôt.",
      heroPointOne: "Lecture en un geste, sans publicité ni inscription.",
      heroPointTwo: "Boucles continues avec fondus doux pour un repos ininterrompu.",
      heroPointThree: "Minuterie et contrôle Apple Watch pour suivre votre rythme.",
      storeTitle: "Prêt pour votre routine du soir",
      storeSubtitle: "Enregistrez cette page et appuyez sur le bouton dès que le lien App Store sera actif.",
      storeButton: "App Store - Bientôt",
      featuresTitle: "Points forts pour un meilleur sommeil",
      feature1Title: "Paysages sonores adaptatifs",
      feature1Body: "Choisissez des mixes conçus pour le sommeil profond, la concentration ou la détente.",
      feature2Title: "Visuels ambiants immersifs",
      feature2Body: "Dégradés doux et animations calmes, sans distraction.",
      feature3Title: "Minuterie adaptée à votre rythme",
      feature3Body: "Réglez des fondus précis pour que le son s'arrête quand vous vous endormez.",
      feature4Title: "Compatibilité Apple Watch",
      feature4Body: "Démarrez, mettez en pause et ajustez depuis votre poignet avec un retour haptique doux.",
      screenshotsTitle: "À l'intérieur de GlowLab AI",
      screenshotsSubtitle: "Découvrez l'application avant de la télécharger."
    }
  },
  privacy: {
    en: {
      privacyBadge: "Effective March 2025",
      privacyTitle: "GlowLab AI Privacy Policy",
      privacyLead: "We keep your relaxation experience private and on your device.",
      privacyOverviewTitle: "1. What this policy covers",
      privacyOverviewText: "This privacy policy explains how GlowLab AI handles information within the iOS and watchOS applications and any companion websites.",
      privacyDataTitle: "2. Data GlowLab AI does not collect",
      privacyDataText: "GlowLab AI does not require you to create an account and does not collect personal data such as your name, email, audio recordings, or sleep habits. All sound selections, timer choices, and personalization stay on your device.",
      privacyOnDeviceTitle: "3. On-device processing",
      privacyOnDeviceText: "Relaxation mixes, playback state, and visual settings are stored in Apple-protected storage on your device. If you delete the app, iOS removes these items automatically. GlowLab AI does not transmit audio or preferences to external servers.",
      privacyPurchasesTitle: "4. Purchases and subscriptions",
      privacyPurchasesText: "If you choose to buy GlowLab AI Premium, the transaction is handled by Apple using your App Store account. We receive confirmation of the purchase status only; no billing or payment details are shared with us.",
      privacyAnalyticsTitle: "5. Diagnostics and analytics",
      privacyAnalyticsText: "We rely on aggregated, anonymous analytics provided by Apple, such as crash reports and basic usage trends, to understand app performance. You can disable sharing diagnostics with developers in iOS Settings > Privacy & Security > Analytics & Improvements.",
      privacyRightsTitle: "6. Your choices",
      privacyRightsText: "You can clear playback history and reset settings at any time inside the app. Removing GlowLab AI from your device deletes all related data. Contact us if you want to request additional privacy actions.",
      privacyContactTitle: "7. Contact",
      privacyContactText: "Email our privacy team:",
      privacyContactEmail: "smfedorov.iosdev@gmail.com",
      privacyContactResponse: "We typically respond within two business days."
    },
    es: {
      privacyBadge: "Vigente desde marzo de 2025",
      privacyTitle: "Política de privacidad de GlowLab AI",
      privacyLead: "Mantenemos tu experiencia de relajación privada y en tu dispositivo.",
      privacyOverviewTitle: "1. Qué cubre esta política",
      privacyOverviewText: "Esta política de privacidad explica cómo GlowLab AI maneja la información dentro de las aplicaciones para iOS y watchOS y cualquier sitio web complementario.",
      privacyDataTitle: "2. Datos que GlowLab AI no recopila",
      privacyDataText: "GlowLab AI no requiere que crees una cuenta y no recopila datos personales como tu nombre, correo, grabaciones de audio o hábitos de sueño. Todas las selecciones de sonido, temporizadores y personalizaciones permanecen en tu dispositivo.",
      privacyOnDeviceTitle: "3. Procesamiento en el dispositivo",
      privacyOnDeviceText: "Las mezclas, el estado de reproducción y los ajustes visuales se guardan en el almacenamiento protegido de Apple. Si eliminas la app, iOS borra estos elementos automáticamente. GlowLab AI no envía audio ni preferencias a servidores externos.",
      privacyPurchasesTitle: "4. Compras y suscripciones",
      privacyPurchasesText: "Si compras GlowLab AI Premium, la transacción la gestiona Apple con tu cuenta de App Store. Solo recibimos la confirmación del estado de la compra; no se comparten datos de facturación ni pagos.",
      privacyAnalyticsTitle: "5. Diagnósticos y analíticas",
      privacyAnalyticsText: "Confiamos en analíticas agregadas y anónimas proporcionadas por Apple, como informes de fallos y tendencias de uso básicas, para entender el rendimiento. Puedes desactivar Compartir análisis con desarrolladores en Ajustes > Privacidad y seguridad > Análisis y mejoras.",
      privacyRightsTitle: "6. Tus opciones",
      privacyRightsText: "Puedes borrar el historial de reproducción y restablecer la app en cualquier momento. Al eliminar GlowLab AI de tu dispositivo se eliminan todos los datos relacionados. Escríbenos si deseas solicitar acciones de privacidad adicionales.",
      privacyContactTitle: "7. Contacto",
      privacyContactText: "Envía un correo a nuestro equipo de privacidad:",
      privacyContactEmail: "smfedorov.iosdev@gmail.com",
      privacyContactResponse: "Respondemos normalmente en un plazo de dos días hábiles."
    },
    ru: {
      privacyBadge: "Актуально с марта 2025 года",
      privacyTitle: "Политика конфиденциальности GlowLab AI",
      privacyLead: "Мы сохраняем ваш опыт расслабления приватным и на вашем устройстве.",
      privacyOverviewTitle: "1. Что охватывает эта политика",
      privacyOverviewText: "Эта политика конфиденциальности объясняет, как GlowLab AI обрабатывает информацию в приложениях для iOS и watchOS, а также на связанных веб-сайтах.",
      privacyDataTitle: "2. Данные, которые GlowLab AI не собирает",
      privacyDataText: "GlowLab AI не требует регистрации и не собирает персональные данные, такие как ваше имя, email, аудиозаписи или привычки сна. Все выборы звуков, таймеры и персонализация остаются на вашем устройстве.",
      privacyOnDeviceTitle: "3. Обработка на устройстве",
      privacyOnDeviceText: "Миксы для расслабления, состояние воспроизведения и визуальные настройки хранятся в защищенном хранилище Apple на вашем устройстве. При удалении приложения iOS автоматически удаляет эти данные. GlowLab AI не передает аудио или предпочтения на внешние серверы.",
      privacyPurchasesTitle: "4. Покупки и подписки",
      privacyPurchasesText: "Если вы покупаете GlowLab AI Premium, платеж обрабатывается Apple через ваш аккаунт App Store. Мы получаем только информацию о статусе покупки; платежные данные нам не передаются.",
      privacyAnalyticsTitle: "5. Диагностика и аналитика",
      privacyAnalyticsText: "Мы используем агрегированные анонимные данные Apple - отчеты о сбоях и базовые тенденции использования - чтобы понимать работу приложения. Вы можете отключить "Делиться аналитикой с разработчиками" в Настройки iOS > Конфиденциальность и безопасность > Аналитика и улучшения.",
      privacyRightsTitle: "6. Ваши возможности",
      privacyRightsText: "Вы можете очистить историю воспроизведения и сбросить настройки в приложении в любой момент. Удаление GlowLab AI с устройства стирает все связанные данные. Свяжитесь с нами для дополнительных запросов по конфиденциальности.",
      privacyContactTitle: "7. Контакты",
      privacyContactText: "Напишите нашей команде по конфиденциальности:",
      privacyContactEmail: "smfedorov.iosdev@gmail.com",
      privacyContactResponse: "Обычно отвечаем в течение двух рабочих дней."
    },
    de: {
      privacyBadge: "Gültig ab März 2025",
      privacyTitle: "GlowLab AI Datenschutzrichtlinie",
      privacyLead: "Wir halten dein Entspannungserlebnis privat und auf deinem Gerät.",
      privacyOverviewTitle: "1. Umfang dieser Richtlinie",
      privacyOverviewText: "Diese Datenschutzrichtlinie erklärt, wie GlowLab AI Informationen in den iOS- und watchOS-Apps sowie auf zugehörigen Websites verarbeitet.",
      privacyDataTitle: "2. Daten, die GlowLab AI nicht sammelt",
      privacyDataText: "GlowLab AI verlangt kein Konto und sammelt keine personenbezogenen Daten wie Name, E-Mail, Audioaufnahmen oder Schlafgewohnheiten. Alle Soundauswahlen, Timer und Anpassungen bleiben auf deinem Gerät.",
      privacyOnDeviceTitle: "3. Verarbeitung auf dem Gerät",
      privacyOnDeviceText: "Mixes, Wiedergabestatus und visuelle Einstellungen werden im von Apple geschützten Speicher deines Geräts abgelegt. Wenn du die App löschst, entfernt iOS diese Daten automatisch. GlowLab AI überträgt keine Audios oder Präferenzen an externe Server.",
      privacyPurchasesTitle: "4. Käufe und Abonnements",
      privacyPurchasesText: "Wenn du GlowLab AI Premium kaufst, wird die Transaktion von Apple über deinen App-Store-Account abgewickelt. Wir erhalten nur die Bestätigung über den Kaufstatus; Zahlungsdaten werden nicht an uns weitergegeben.",
      privacyAnalyticsTitle: "5. Diagnosen und Analysen",
      privacyAnalyticsText: "Wir stützen uns auf aggregierte, anonyme Analysen von Apple, z. B. Absturzberichte und grundlegende Nutzungstrends, um die Leistung zu verstehen. Du kannst das Teilen von Analysen unter Einstellungen > Datenschutz & Sicherheit > Analyse & Verbesserungen deaktivieren.",
      privacyRightsTitle: "6. Deine Wahlmöglichkeiten",
      privacyRightsText: "Du kannst die Wiedergabeverläufe löschen und die Einstellungen jederzeit in der App zurücksetzen. Durch das Entfernen von GlowLab AI vom Gerät werden alle zugehörigen Daten gelöscht. Kontaktiere uns für weitere Datenschutzanfragen.",
      privacyContactTitle: "7. Kontakt",
      privacyContactText: "Schreibe an unser Datenschutzteam:",
      privacyContactEmail: "smfedorov.iosdev@gmail.com",
      privacyContactResponse: "Wir antworten in der Regel innerhalb von zwei Werktagen."
    },
    it: {
      privacyBadge: "In vigore da marzo 2025",
      privacyTitle: "Informativa sulla privacy di GlowLab AI",
      privacyLead: "Manteniamo la tua esperienza di relax privata e sul tuo dispositivo.",
      privacyOverviewTitle: "1. Ambito di questa informativa",
      privacyOverviewText: "Questa informativa spiega come GlowLab AI gestisce le informazioni nelle app iOS e watchOS e in eventuali siti web collegati.",
      privacyDataTitle: "2. Dati che GlowLab AI non raccoglie",
      privacyDataText: "GlowLab AI non richiede la creazione di un account e non raccoglie dati personali come nome, email, registrazioni audio o abitudini di sonno. Tutte le scelte di suoni, timer e personalizzazioni restano sul dispositivo.",
      privacyOnDeviceTitle: "3. Elaborazione sul dispositivo",
      privacyOnDeviceText: "Le combinazioni sonore, lo stato di riproduzione e le impostazioni visive sono archiviati nello spazio protetto da Apple sul tuo dispositivo. Eliminando l'app, iOS rimuove automaticamente tali dati. GlowLab AI non invia audio o preferenze a server esterni.",
      privacyPurchasesTitle: "4. Acquisti e abbonamenti",
      privacyPurchasesText: "Se acquisti GlowLab AI Premium, la transazione è gestita da Apple tramite il tuo account App Store. Riceviamo solo la conferma dello stato dell'acquisto; i dettagli di pagamento non ci vengono comunicati.",
      privacyAnalyticsTitle: "5. Diagnostica e analisi",
      privacyAnalyticsText: "Ci basiamo su analisi aggregate e anonime fornite da Apple, come report sugli arresti anomali e tendenze d'uso, per comprendere le prestazioni. Puoi disattivare Condividi analisi con gli sviluppatori in Impostazioni > Privacy e sicurezza > Analisi e miglioramenti.",
      privacyRightsTitle: "6. Le tue scelte",
      privacyRightsText: "Puoi cancellare la cronologia di riproduzione e ripristinare le impostazioni in qualsiasi momento. Rimuovendo GlowLab AI dal dispositivo elimini anche tutti i dati associati. Contattaci per eventuali richieste aggiuntive sulla privacy.",
      privacyContactTitle: "7. Contatti",
      privacyContactText: "Scrivi al nostro team privacy:",
      privacyContactEmail: "smfedorov.iosdev@gmail.com",
      privacyContactResponse: "Rispondiamo di solito entro due giorni lavorativi."
    },
    fr: {
      privacyBadge: "En vigueur depuis mars 2025",
      privacyTitle: "Politique de confidentialité de GlowLab AI",
      privacyLead: "Nous gardons votre expérience de détente privée et sur votre appareil.",
      privacyOverviewTitle: "1. Portée de cette politique",
      privacyOverviewText: "Cette politique de confidentialité explique comment GlowLab AI gère les informations dans les applications iOS et watchOS ainsi que sur les sites associés.",
      privacyDataTitle: "2. Données que GlowLab AI ne collecte pas",
      privacyDataText: "GlowLab AI ne nécessite pas de créer un compte et ne collecte pas de données personnelles telles que nom, e-mail, enregistrements audio ou habitudes de sommeil. Tous les choix de sons, minuteries et personnalisations restent sur votre appareil.",
      privacyOnDeviceTitle: "3. Traitement sur l'appareil",
      privacyOnDeviceText: "Les mixes, l'état de lecture et les réglages visuels sont stockés dans l'espace protégé par Apple de votre appareil. Si vous supprimez l'app, iOS efface automatiquement ces données. GlowLab AI n'envoie aucun audio ni préférence à des serveurs externes.",
      privacyPurchasesTitle: "4. Achats et abonnements",
      privacyPurchasesText: "Si vous achetez GlowLab AI Premium, la transaction est gérée par Apple via votre compte App Store. Nous recevons uniquement la confirmation de l'état d'achat ; aucun détail de paiement ne nous est transmis.",
      privacyAnalyticsTitle: "5. Diagnostics et analyses",
      privacyAnalyticsText: "Nous utilisons les analyses agrégées et anonymes fournies par Apple, comme les rapports de plantage et les tendances d'usage, pour comprendre les performances. Vous pouvez désactiver Partager les analyses avec les développeurs dans Réglages > Confidentialité et sécurité > Analyses et améliorations.",
      privacyRightsTitle: "6. Vos choix",
      privacyRightsText: "Vous pouvez effacer l'historique de lecture et réinitialiser les réglages à tout moment. La suppression de GlowLab AI de votre appareil efface toutes les données associées. Contactez-nous pour toute demande supplémentaire.",
      privacyContactTitle: "7. Contact",
      privacyContactText: "Envoyez un e-mail à notre équipe confidentialité :",
      privacyContactEmail: "smfedorov.iosdev@gmail.com",
      privacyContactResponse: "Nous répondons généralement sous deux jours ouvrables."
    }
  },
  support: {
    en: {
      supportBadge: "Need help?",
      supportTitle: "GlowLab AI Support",
      supportLead: "Find quick fixes, request features, or contact the team directly.",
      supportCard1Title: "If the audio is silent",
      supportCard1Body: "Follow these steps to restore playback.",
      supportCard1Step1: "Make sure the device is not muted and system volume is above 50%.",
      supportCard1Step2: "Open GlowLab AI, pause the session, and start it again after 3 seconds.",
      supportCard1Step3: "Restart your device if the issue appears across other apps.",
      supportCard2Title: "Restore Premium access",
      supportCard2Body: "Use App Store purchase history to unlock existing purchases.",
      supportCard2Step1: "Open GlowLab AI -> Settings -> Premium.",
      supportCard2Step2: "Tap \"Restore purchases\" and confirm with your Apple ID.",
      supportCard2Step3: "Ensure you are signed in with the same Apple ID used for the original purchase.",
      supportCard3Title: "Share improvement ideas",
      supportCard3Body: "Your feedback shapes the next updates.",
      supportCard3Step1: "Tell us which soundscapes or visuals you would love to see next.",
      supportCard3Step2: "Mention your device model and iOS version for context.",
      supportCard3Step3: "Attach screenshots or short clips if they help explain the request.",
      supportContactTitle: "Contact us",
      supportContactText: "Email our support team with a short description of the issue or idea.",
      supportContactEmail: "smfedorov.iosdev@gmail.com",
      supportMetaTime: "We reply within two business days.",
      supportMetaLanguages: "Support available in English, Spanish, and Russian."
    },
    es: {
      supportBadge: "¿Necesitas ayuda?",
      supportTitle: "Soporte de GlowLab AI",
      supportLead: "Encuentra soluciones rápidas, solicita funciones o contacta al equipo.",
      supportCard1Title: "Si el audio está en silencio",
      supportCard1Body: "Sigue estos pasos para recuperar la reproducción.",
      supportCard1Step1: "Asegúrate de que el dispositivo no esté en silencio y que el volumen supere el 50%.",
      supportCard1Step2: "Abre GlowLab AI, pausa la sesión y reanúdala después de 3 segundos.",
      supportCard1Step3: "Reinicia el dispositivo si el problema aparece también en otras apps.",
      supportCard2Title: "Restaurar acceso Premium",
      supportCard2Body: "Utiliza el historial de compras de App Store para recuperar tus compras.",
      supportCard2Step1: "Abre GlowLab AI -> Ajustes -> Premium.",
      supportCard2Step2: "Toca \"Restaurar compras\" y confirma con tu Apple ID.",
      supportCard2Step3: "Verifica que usas el mismo Apple ID de la compra original.",
      supportCard3Title: "Comparte ideas de mejora",
      supportCard3Body: "Tus comentarios inspiran las próximas actualizaciones.",
      supportCard3Step1: "Cuéntanos qué paisajes sonoros o visuales te gustaría recibir.",
      supportCard3Step2: "Indica el modelo de tu dispositivo y la versión de iOS para darnos contexto.",
      supportCard3Step3: "Adjunta capturas o vídeos cortos si ayudan a explicar la solicitud.",
      supportContactTitle: "Contáctanos",
      supportContactText: "Escribe al equipo de soporte con una breve descripción del problema o idea.",
      supportContactEmail: "smfedorov.iosdev@gmail.com",
      supportMetaTime: "Respondemos en un plazo de dos días hábiles.",
      supportMetaLanguages: "Soporte disponible en inglés, español y ruso."
    },
    ru: {
      supportBadge: "Нужна помощь?",
      supportTitle: "Поддержка GlowLab AI",
      supportLead: "Найдите быстрые решения, предложите идеи или свяжитесь с командой напрямую.",
      supportCard1Title: "Если нет звука",
      supportCard1Body: "Следуйте этим шагам, чтобы восстановить воспроизведение.",
      supportCard1Step1: "Убедитесь, что устройство не в беззвучном режиме и громкость выше 50%.",
      supportCard1Step2: "Откройте GlowLab AI, поставьте сессию на паузу и запустите снова через 3 секунды.",
      supportCard1Step3: "Перезагрузите устройство, если проблема проявляется и в других приложениях.",
      supportCard2Title: "Восстановление Premium",
      supportCard2Body: "Используйте историю покупок App Store, чтобы вернуть доступ.",
      supportCard2Step1: "Откройте GlowLab AI -> Настройки -> Premium.",
      supportCard2Step2: "Нажмите \"Восстановить покупки\" и подтвердите Apple ID.",
      supportCard2Step3: "Убедитесь, что вы вошли под тем же Apple ID, что и при покупке.",
      supportCard3Title: "Поделитесь идеями",
      supportCard3Body: "Ваши пожелания помогают планировать обновления.",
      supportCard3Step1: "Расскажите, какие звуки или визуализации хотите увидеть дальше.",
      supportCard3Step2: "Укажите модель устройства и версию iOS для контекста.",
      supportCard3Step3: "Приложите скриншоты или короткие видео, если это помогает объяснить запрос.",
      supportContactTitle: "Свяжитесь с нами",
      supportContactText: "Напишите в службу поддержки с кратким описанием проблемы или идеи.",
      supportContactEmail: "smfedorov.iosdev@gmail.com",
      supportMetaTime: "Отвечаем в течение двух рабочих дней.",
      supportMetaLanguages: "Поддержка доступна на английском, испанском и русском языках."
    },
    de: {
      supportBadge: "Brauchst du Hilfe?",
      supportTitle: "GlowLab AI Support",
      supportLead: "Finde schnelle Lösungen, fordere Funktionen an oder kontaktiere das Team direkt.",
      supportCard1Title: "Wenn kein Ton zu hören ist",
      supportCard1Body: "Befolge diese Schritte, um die Wiedergabe wiederherzustellen.",
      supportCard1Step1: "Stelle sicher, dass das Gerät nicht stumm geschaltet ist und die Lautstärke über 50% liegt.",
      supportCard1Step2: "Öffne GlowLab AI, pausiere die Sitzung und starte sie nach 3 Sekunden erneut.",
      supportCard1Step3: "Starte dein Gerät neu, falls das Problem auch in anderen Apps auftritt.",
      supportCard2Title: "Premium-Zugang wiederherstellen",
      supportCard2Body: "Nutze den App-Store-Kaufverlauf, um frühere Käufe zu aktivieren.",
      supportCard2Step1: "Öffne GlowLab AI -> Einstellungen -> Premium.",
      supportCard2Step2: "Tippe auf \"Käufe wiederherstellen\" und bestätige mit deiner Apple-ID.",
      supportCard2Step3: "Stelle sicher, dass du mit derselben Apple-ID angemeldet bist wie beim ursprünglichen Kauf.",
      supportCard3Title: "Verbesserungsideen teilen",
      supportCard3Body: "Dein Feedback gestaltet die nächsten Updates.",
      supportCard3Step1: "Sag uns, welche Klanglandschaften oder Visuals du als Nächstes möchtest.",
      supportCard3Step2: "Nenne dein Gerätemodell und die iOS-Version für den Kontext.",
      supportCard3Step3: "Füge Screenshots oder kurze Clips bei, wenn sie die Anfrage verdeutlichen.",
      supportContactTitle: "Kontaktiere uns",
      supportContactText: "Schreibe dem Support-Team eine kurze Beschreibung des Problems oder der Idee.",
      supportContactEmail: "smfedorov.iosdev@gmail.com",
      supportMetaTime: "Wir antworten innerhalb von zwei Werktagen.",
      supportMetaLanguages: "Support verfügbar auf Englisch, Spanisch und Russisch."
    },
    it: {
      supportBadge: "Serve aiuto?",
      supportTitle: "Supporto GlowLab AI",
      supportLead: "Trova soluzioni rapide, richiedi funzioni o contatta direttamente il team.",
      supportCard1Title: "Se l'audio è silenzioso",
      supportCard1Body: "Segui questi passaggi per ripristinare la riproduzione.",
      supportCard1Step1: "Assicurati che il dispositivo non sia in modalità silenziosa e che il volume superi il 50%.",
      supportCard1Step2: "Apri GlowLab AI, metti in pausa la sessione e riavviala dopo 3 secondi.",
      supportCard1Step3: "Riavvia il dispositivo se il problema compare anche in altre app.",
      supportCard2Title: "Ripristina l'accesso Premium",
      supportCard2Body: "Usa la cronologia degli acquisti App Store per sbloccare gli acquisti esistenti.",
      supportCard2Step1: "Apri GlowLab AI -> Impostazioni -> Premium.",
      supportCard2Step2: "Tocca \"Ripristina acquisti\" e conferma con l'Apple ID.",
      supportCard2Step3: "Verifica di aver effettuato l'accesso con lo stesso Apple ID dell'acquisto iniziale.",
      supportCard3Title: "Condividi idee di miglioramento",
      supportCard3Body: "Il tuo feedback guida i prossimi aggiornamenti.",
      supportCard3Step1: "Dicci quali suoni o visual desideri vedere in futuro.",
      supportCard3Step2: "Indica il modello del dispositivo e la versione di iOS.",
      supportCard3Step3: "Allega screenshot o clip brevi se aiutano a spiegare la richiesta.",
      supportContactTitle: "Contattaci",
      supportContactText: "Invia al supporto una breve descrizione del problema o dell'idea.",
      supportContactEmail: "smfedorov.iosdev@gmail.com",
      supportMetaTime: "Rispondiamo entro due giorni lavorativi.",
      supportMetaLanguages: "Supporto disponibile in inglese, spagnolo e russo."
    },
    fr: {
      supportBadge: "Besoin d'aide ?",
      supportTitle: "Support GlowLab AI",
      supportLead: "Trouvez des solutions rapides, proposez des idées ou contactez l'équipe.",
      supportCard1Title: "Si le son est coupé",
      supportCard1Body: "Suivez ces étapes pour rétablir la lecture.",
      supportCard1Step1: "Vérifiez que l'appareil n'est pas en mode silencieux et que le volume dépasse 50%.",
      supportCard1Step2: "Ouvrez GlowLab AI, mettez la session en pause puis relancez-la après 3 secondes.",
      supportCard1Step3: "Redémarrez l'appareil si le problème survient aussi dans d'autres apps.",
      supportCard2Title: "Restaurer l'accès Premium",
      supportCard2Body: "Utilisez l'historique d'achats App Store pour réactiver vos achats.",
      supportCard2Step1: "Ouvrez GlowLab AI -> Réglages -> Premium.",
      supportCard2Step2: "Touchez \"Restaurer les achats\" et confirmez avec votre identifiant Apple.",
      supportCard2Step3: "Assurez-vous d'être connecté avec le même identifiant Apple que lors de l'achat.",
      supportCard3Title: "Partager des idées d'amélioration",
      supportCard3Body: "Vos retours guident les prochaines mises à jour.",
      supportCard3Step1: "Indiquez quels paysages sonores ou visuels vous souhaitez découvrir.",
      supportCard3Step2: "Précisez le modèle de l'appareil et la version d'iOS pour le contexte.",
      supportCard3Step3: "Ajoutez des captures d'écran ou de courtes vidéos si elles clarifient la demande.",
      supportContactTitle: "Contactez-nous",
      supportContactText: "Envoyez au support une brève description du problème ou de l'idée.",
      supportContactEmail: "smfedorov.iosdev@gmail.com",
      supportMetaTime: "Nous répondons sous deux jours ouvrables.",
      supportMetaLanguages: "Support disponible en anglais, espagnol et russe."
    }
  },
  copyright: {
    en: {
      copyrightBadge: "Brand guidelines",
      copyrightTitle: "GlowLab AI Copyright Notice",
      copyrightLead: "Understand how to reference GlowLab AI assets in press, reviews, and promotions.",
      copyrightAppTitle: "1. Ownership",
      copyrightAppText: "GlowLab AI, including all code, design elements, visuals, sounds, and documentation, is owned by the GlowLab AI team. All rights are reserved unless you receive written permission stating otherwise.",
      copyrightAssetsTitle: "2. Screenshots and media",
      copyrightAssetsText: "Official screenshots, iconography, and promotional graphics may be used for editorial coverage of GlowLab AI as long as the assets are not altered beyond simple resizing or cropping.",
      copyrightUsageTitle: "3. Permitted uses",
      copyrightUsageItem1: "Share GlowLab AI publicly with clear attribution.",
      copyrightUsageItem2: "Publish reviews, tutorials, or educational content using original screenshots.",
      copyrightUsageItem3: "Embed the GlowLab AI app icon when linking to our official App Store listing.",
      copyrightRestrictionsTitle: "4. Restrictions",
      copyrightRestrictionsText: "You may not sell GlowLab AI assets, use them to imply partnership, or remix them into competing applications. Do not change colors, add overlays, or place the brand in misleading contexts.",
      copyrightNoticeTitle: "5. Trademarks and acknowledgements",
      copyrightNoticeText: "GlowLab AI, the GlowLab AI logo, and related marks are trademarks of the GlowLab AI team. Apple, iPhone, and Apple Watch are trademarks of Apple Inc. and are mentioned for context only.",
      copyrightContactTitle: "6. Contact",
      copyrightContactText: "Request additional permissions or report misuse via email:",
      copyrightContactEmail: "smfedorov.iosdev@gmail.com",
      copyrightContactResponse: "Include links or reference materials so we can respond quickly."
    },
    es: {
      copyrightBadge: "Guía de marca",
      copyrightTitle: "Aviso de derechos de autor de GlowLab AI",
      copyrightLead: "Conoce cómo referenciar los recursos de GlowLab AI en prensa, reseñas y promociones.",
      copyrightAppTitle: "1. Titularidad",
      copyrightAppText: "GlowLab AI, incluido el código, los elementos de diseño, los visuales, los sonidos y la documentación, pertenece al equipo de GlowLab AI. Todos los derechos están reservados salvo permiso escrito en contrario.",
      copyrightAssetsTitle: "2. Capturas y material gráfico",
      copyrightAssetsText: "Las capturas oficiales, iconos y gráficos promocionales pueden usarse para cobertura editorial de GlowLab AI siempre que solo se redimensionen o recorten de forma sencilla.",
      copyrightUsageTitle: "3. Usos permitidos",
      copyrightUsageItem1: "Compartir GlowLab AI públicamente con una atribución clara.",
      copyrightUsageItem2: "Publicar reseñas, tutoriales o contenido educativo con capturas originales.",
      copyrightUsageItem3: "Incluir el icono de la app al enlazar a la ficha oficial en App Store.",
      copyrightRestrictionsTitle: "4. Restricciones",
      copyrightRestrictionsText: "No puedes vender los recursos de GlowLab AI, insinuar asociaciones ni reutilizarlos en apps competidoras. No cambies los colores ni coloques la marca en contextos engañosos.",
      copyrightNoticeTitle: "5. Marcas y reconocimientos",
      copyrightNoticeText: "GlowLab AI, su logotipo y las marcas relacionadas son propiedad del equipo GlowLab AI. Apple, iPhone y Apple Watch son marcas de Apple Inc. y se mencionan solo como referencia.",
      copyrightContactTitle: "6. Contacto",
      copyrightContactText: "Solicita permisos adicionales o informa sobre usos indebidos por correo:",
      copyrightContactEmail: "smfedorov.iosdev@gmail.com",
      copyrightContactResponse: "Incluye enlaces o materiales de referencia para que podamos responder rápido."
    },
    ru: {
      copyrightBadge: "Руководство по бренду",
      copyrightTitle: "Уведомление об авторских правах GlowLab AI",
      copyrightLead: "Узнайте, как использовать материалы GlowLab AI в публикациях, обзорах и промо.",
      copyrightAppTitle: "1. Правообладатель",
      copyrightAppText: "GlowLab AI, включая код, дизайн, визуалы, звуки и документацию, принадлежит команде GlowLab AI. Все права защищены, если иное не согласовано письменно.",
      copyrightAssetsTitle: "2. Скриншоты и медиа",
      copyrightAssetsText: "Официальные скриншоты, иконки и промо-графику можно использовать в редакционных материалах о GlowLab AI при условии, что изменения ограничиваются размером и кадрированием.",
      copyrightUsageTitle: "3. Разрешенное использование",
      copyrightUsageItem1: "Публиковать информацию о GlowLab AI с указанием источника.",
      copyrightUsageItem2: "Размещать обзоры, инструкции и обучающие материалы с оригинальными скриншотами.",
      copyrightUsageItem3: "Использовать иконку приложения при ссылке на официальную страницу в App Store.",
      copyrightRestrictionsTitle: "4. Ограничения",
      copyrightRestrictionsText: "Запрещено продавать материалы GlowLab AI, намекать на партнерство или перерабатывать их для конкурирующих приложений. Не изменяйте цвета и не используйте бренд в вводящем в заблуждение контексте.",
      copyrightNoticeTitle: "5. Товарные знаки",
      copyrightNoticeText: "GlowLab AI, логотип GlowLab AI и связанные обозначения являются товарными знаками команды GlowLab AI. Apple, iPhone и Apple Watch - товарные знаки Apple Inc. и упоминаются только для контекста.",
      copyrightContactTitle: "6. Контакты",
      copyrightContactText: "Запросите дополнительные разрешения или сообщите о нарушении по email:",
      copyrightContactEmail: "smfedorov.iosdev@gmail.com",
      copyrightContactResponse: "Добавьте ссылки или материалы, чтобы мы ответили быстрее."
    },
    de: {
      copyrightBadge: "Markenrichtlinien",
      copyrightTitle: "Urheberrechtshinweis zu GlowLab AI",
      copyrightLead: "Erfahre, wie du GlowLab AI in Presse, Reviews und Promotions referenzieren darfst.",
      copyrightAppTitle: "1. Eigentum",
      copyrightAppText: "GlowLab AI mit seinem Code, Design, Visuals, Sounds und der Dokumentation gehört dem GlowLab-AI-Team. Alle Rechte bleiben vorbehalten, sofern keine schriftliche Erlaubnis vorliegt.",
      copyrightAssetsTitle: "2. Screenshots und Medien",
      copyrightAssetsText: "Offizielle Screenshots, Icons und Promo-Grafiken dürfen für redaktionelle Beiträge über GlowLab AI verwendet werden, solange nur einfaches Zuschneiden oder Skalieren erfolgt.",
      copyrightUsageTitle: "3. Erlaubte Nutzung",
      copyrightUsageItem1: "GlowLab AI öffentlich mit klarer Quellenangabe teilen.",
      copyrightUsageItem2: "Reviews, Tutorials oder Lerninhalte mit Original-Screenshots veröffentlichen.",
      copyrightUsageItem3: "Das App-Icon einbinden, wenn auf den offiziellen App-Store-Link verwiesen wird.",
      copyrightRestrictionsTitle: "4. Einschränkungen",
      copyrightRestrictionsText: "Es ist untersagt, GlowLab-AI-Assets zu verkaufen, Partnerschaften vorzutäuschen oder sie in konkurrierenden Apps zu verwenden. Ändere keine Farben und platziere die Marke nicht in irreführenden Kontexten.",
      copyrightNoticeTitle: "5. Marken und Hinweise",
      copyrightNoticeText: "GlowLab AI, das GlowLab-AI-Logo und verwandte Kennzeichen sind Marken des GlowLab-AI-Teams. Apple, iPhone und Apple Watch sind Marken von Apple Inc. und werden nur als Referenz genannt.",
      copyrightContactTitle: "6. Kontakt",
      copyrightContactText: "Fordere zusätzliche Genehmigungen an oder melde Missbrauch per E-Mail:",
      copyrightContactEmail: "smfedorov.iosdev@gmail.com",
      copyrightContactResponse: "Füge Links oder Referenzen bei, damit wir schnell reagieren können."
    },
    it: {
      copyrightBadge: "Linee guida del brand",
      copyrightTitle: "Avviso sul copyright di GlowLab AI",
      copyrightLead: "Scopri come citare le risorse di GlowLab AI in articoli, recensioni e promozioni.",
      copyrightAppTitle: "1. Titolarità",
      copyrightAppText: "GlowLab AI, compresi codice, design, visual, suoni e documentazione, è di proprietà del team GlowLab AI. Tutti i diritti sono riservati salvo autorizzazione scritta.",
      copyrightAssetsTitle: "2. Screenshot e media",
      copyrightAssetsText: "Screenshot ufficiali, icone e grafica promozionale possono essere usati per copertura editoriale di GlowLab AI purché le modifiche si limitino a ridimensionamento o ritaglio.",
      copyrightUsageTitle: "3. Usi consentiti",
      copyrightUsageItem1: "Condividere GlowLab AI pubblicamente con chiara attribuzione.",
      copyrightUsageItem2: "Pubblicare recensioni, tutorial o contenuti educativi con screenshot originali.",
      copyrightUsageItem3: "Inserire l'icona dell'app quando si collega alla pagina ufficiale su App Store.",
      copyrightRestrictionsTitle: "4. Limitazioni",
      copyrightRestrictionsText: "Non è consentito vendere le risorse di GlowLab AI, suggerire partnership o riutilizzarle in app concorrenti. Non modificare i colori né usare il brand in contesti fuorvianti.",
      copyrightNoticeTitle: "5. Marchi registrati",
      copyrightNoticeText: "GlowLab AI, il logo GlowLab AI e i marchi correlati sono marchi del team GlowLab AI. Apple, iPhone e Apple Watch sono marchi di Apple Inc. e vengono citati solo come riferimento.",
      copyrightContactTitle: "6. Contatti",
      copyrightContactText: "Richiedi permessi aggiuntivi o segnala abusi via email:",
      copyrightContactEmail: "smfedorov.iosdev@gmail.com",
      copyrightContactResponse: "Includi link o materiali di riferimento per una risposta rapida."
    },
    fr: {
      copyrightBadge: "Guide de marque",
      copyrightTitle: "Avis sur les droits d'auteur de GlowLab AI",
      copyrightLead: "Découvrez comment mentionner les ressources GlowLab AI dans la presse, les avis et les promotions.",
      copyrightAppTitle: "1. Propriété",
      copyrightAppText: "GlowLab AI, son code, son design, ses visuels, ses sons et sa documentation appartiennent à l'équipe GlowLab AI. Tous droits réservés sauf autorisation écrite.",
      copyrightAssetsTitle: "2. Captures et médias",
      copyrightAssetsText: "Vous pouvez utiliser les captures, icônes et visuels officiels pour parler de GlowLab AI, à condition de ne faire que des recadrages ou redimensionnements simples.",
      copyrightUsageTitle: "3. Usages autorisés",
      copyrightUsageItem1: "Partager GlowLab AI publiquement avec attribution claire.",
      copyrightUsageItem2: "Publier critiques, tutoriels ou contenus pédagogiques avec des captures originales.",
      copyrightUsageItem3: "Intégrer l'icône de l'app en renvoyant vers la fiche officielle sur l'App Store.",
      copyrightRestrictionsTitle: "4. Restrictions",
      copyrightRestrictionsText: "Il est interdit de vendre les ressources GlowLab AI, de suggérer un partenariat ou de les réutiliser dans des apps concurrentes. Ne modifiez pas les couleurs et n'utilisez pas la marque dans un contexte trompeur.",
      copyrightNoticeTitle: "5. Marques et mentions",
      copyrightNoticeText: "GlowLab AI, son logo et les marques associées appartiennent à l'équipe GlowLab AI. Apple, iPhone et Apple Watch sont des marques d'Apple Inc. mentionnées uniquement à titre de référence.",
      copyrightContactTitle: "6. Contact",
      copyrightContactText: "Demandez des autorisations supplémentaires ou signalez un usage abusif par e-mail :",
      copyrightContactEmail: "smfedorov.iosdev@gmail.com",
      copyrightContactResponse: "Ajoutez des liens ou documents pour que nous puissions répondre rapidement."
    }
  }
};

const supportedLanguages = ["en", "es", "ru", "de", "it", "fr"];

function getDefaultLanguage() {
  const stored = window.localStorage.getItem("glowlab-language");
  if (stored && supportedLanguages.includes(stored)) {
    return stored;
  }
  const browser = navigator.language ? navigator.language.slice(0, 2).toLowerCase() : "en";
  return supportedLanguages.includes(browser) ? browser : "en";
}

function mergeTranslations(lang, page) {
  const fallback = translations.common.en;
  const common = translations.common[lang] || fallback;
  const pageTranslations = translations[page]?.[lang] || translations[page]?.en || {};
  return { ...fallback, ...common, ...pageTranslations };
}

function applyLanguage(lang, page) {
  const merged = mergeTranslations(lang, page);
  document.documentElement.lang = lang;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (!key) return;
    const value = merged[key];
    if (value) {
      element.textContent = value;
    }
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const page = document.body.dataset.page || "home";
  const picker = document.querySelector('[data-role="language-picker"]');
  const initialLang = getDefaultLanguage();

  if (picker) {
    picker.value = initialLang;
    picker.addEventListener("change", (event) => {
      const lang = event.target.value;
      window.localStorage.setItem("glowlab-language", lang);
      applyLanguage(lang, page);
    });
  }

  applyLanguage(initialLang, page);
});
